image: node:lts

definitions:
  steps:
    - step: &install-e2e-tests-server-on-test-geoportal
        name: install masterportals master, basic etc. on test.geoportal
        caches:
            - node
        artifacts:
            - dist/**
        script:
            - export FTP_USERNAME="$LGV_TEST_FTP_USERNAME"
            - export FTP_PASSWORD="$LGV_TEST_FTP_PASSWORD"
            - export FTP_SOURCE_PATH="dist"
            - export FTP_TARGET_URL="ftp://test.geoportal-hamburg.de/"
            - export FTP_GITLOGFILE="testGitLog"
            #replace slashes in branchname with underscores
            - tmp=$BITBUCKET_BRANCH
            - branchname=${tmp//[\/]/_}
            - export FTP_UNTRACKED_PATH=$'!dist/master_'$branchname$'\n!dist/basic_'$branchname$'\n!dist/masterCustom_'$branchname$'\n!dist/masterDefault_'$branchname$'\n!dist/mastercode'
            - git clone git@bitbucket.org:geowerkstatt-hamburg/ci_scripts.git
            - mv ./ci_scripts/deployScripts ./deployScripts # mv deployScripts scripts to masterportal root
            - rm -rf ./ci_scripts
            - rm -rf ./addons/readme.txt
            # because of use of "git-ftp" for transfering files every change in repository has to be comittet, see https://git-ftp.github.io/
            - git commit ./addons/readme.txt -m "deleted before add addons in e2e test run"
            - git clone https://geowerkstatt@bitbucket.org/geowerkstatt-hamburg/addons.git
            - cd addons
            - find . -maxdepth 2 -name package.json -execdir npm i \;
            - cd ..;
            - npm install
            - npm run buildPortal
            - apt-get update && apt-get install unzip
            # make script executable
            - chmod +x ./deployScripts/transfer_ftp.sh
            # commit changed file for "git-ftp"
            - /bin/bash ./deployScripts/transfer_ftp.sh

pipelines:
    # Start pipeline with tag to build examples zips and copy them to the Bitbucket download folder
    tags:
        'v*.*.*':
            - step:
                name: build examples zip
                caches:
                    - node
                artifacts:
                    - dist/**
                script:
                    - npm install
                    - npm run buildExamples
                    - apt-get update
            - step:
                name: deploy examples zip
                caches:
                    - node
                script:
                    - apt-get install -y curl
                    # find all zip folders in dist folder, loop through the results and post the zips to the BB download folder
                    - for zipFilePath in $(find dist -name \*.zip); do
                        curl -X POST --user "$bbapi_name:$bbapi_key" "https://api.bitbucket.org/2.0/repositories/geowerkstatt-hamburg/masterportal/downloads" --form files=@"$zipFilePath" --verbose;
                      done
    custom: # Pipelines that are triggered manually
        End2End-Tests on saucelabs:
            - step: *install-e2e-tests-server-on-test-geoportal
            - step:
                name: run e2e tests on saucelabs url=test.geoportal
                caches:
                    - node
                script:
                    # run e2e tests
                    - export url=https://test.geoportal-hamburg.de
                    - npm run browsertestOnExternalServer --testservice=saucelabs
        End2End-Tests on saucelabs/ use existing server:
            - step:
                name: run e2e tests on saucelabs url=test.geoportal_buildname
                caches:
                    - node
                script:
                    - export url=https://test.geoportal-hamburg.de
                    - npm run browsertestOnExternalServer --testservice=saucelabs
